@startuml Clinique Veterinaire
skinparam Style strictuml
skinparam SequenceMessageAlignment center

abstract class Personne <<abstract>> {
    nom : String 
    prenom : String
    date_naissance : Date
    adresse : String
    telephone : Integer
    periode : Date 
}

class Personnel {
    id : Integer
    poste : Boolean 
}

class Veterinaire

class Assistant

class Client {
    id : Integer
}

class Animal {
    id : Integer
    nom : String
    date_naissance : Date 
    num_puce : Integer
    num_passeport : Integer
    proprietaires : List
    date_adoption : Date
}

class Categorie_Espece{
    list_espece : List
    autre_espece : String
}

class Medicament {
    nom : String
    description : Text
}

class Traitement {
    debut : Date
    duree : Date 
    nom : String
    quantite : Integer

}

class Dossier_Medical {
    id : Integer 
    taille : Integer
    poids : Integer
    resultat : String
    observation : String
    date : Date 
    heure : Time 
}

class Procedure{
    nom : String
    description : Text 
}

class dosage {
    quantite : Integer
}

class historique_veto {
    date_debut : Date
}


Medicament "1..*" - "1..*" Traitement
(Medicament, Traitement) .. dosage

Personne <|-- Personnel
Personne <|-- Client

Personnel <|-- Assistant
Personnel <|-- Veterinaire
Personnel "*" -- "1" Categorie_Espece : est specialise >
Personnel "1" -- "1..* " Animal : < suivi par
(Animal, Personnel) .. historique_veto

Animal "1..* " -- "1" Categorie_Espece : est de >
Animal "1..* " -- "1 ..*" Client : < possede
Animal o-- "0..1" Dossier_Medical : < appartient a 

Dossier_Medical "1..* " -- "1..*" Traitement : comporte >
Dossier_Medical "1..* " -- "1" Procedure : possede >

Veterinaire "1..* " -- "1..*" Traitement : prescrit >

Medicament "0..* " -- "0..*" Categorie_Espece : est autorise > 

note "le <b>personnel</b> de la clinique ne doit pas avoir d'<b>animaux</b> de compagnie traités dans la clinique" as N1
Personnel .. N1
N1 .. Animal

@enduml
